spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_jobfair?serverTimezone=UTC&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    show-sql: true
